### ISSUE TITLE
Cloudflare tunnel (Solved)

### ISSUE THREAD

**Issue by hsmptg** [n-stone/docker-bastillion#2]
Hi
An easy way to have https accesses to my web services running in my Home server without having to open ports is to use Cloudflare tunnels. This process works with services like Node-RED, InfluxDB, Grafana, etc. but not with Bastillion. Note that if I open locally (that is inside the server) the url https://127.0.0.1:8443, all works OK which means that the container is running well.
Do you know what could cause this?
Regards and congratulations for this project.

**Comment by mietzen** [comment]
Thanks!
Sorry I'm not familiar with Cloudflare tunnels, it's actually first time hearing of it.
Can you open a ticket or something at cloudflare? I think they might be able to help. 

I closing this since the container itself runs fine.

**Comment by hsmptg** [comment]
Ok, thanks!
Just a last question: I noticed that if I try to open http://127.0.0.1:8443 in the server I get a page with a couple of strange characters: �P
Only when I open https://127.0.0.1:8443 I can access the login page.
Is this normal?
Regards

**Comment by mietzen** [comment]
Depending on what browser you using you should get something like a `ERR_INVALID_HTTP_RESPONSE`. So it's 'normal' it is not working because you trying to read a https page as if it is a non encrypted http page.

If you need plain http for Cloudflare tunnels to work see: https://github.com/mietzen/docker-bastillion/issues/3#issuecomment-1273357546

But you should never ever expose the plain http interface to the web, this should only be used behind a proxy that takes care of the encryption.

**Comment by hsmptg** [comment]
Meanwhile I solved the problem: during the Cloudflare tunnel creation wizard, I just had to choose in the “Public Hostname Page” a service Type: HTTPS and then (this is the solution) in the “Additional application settings” enable the “No TLS Verify” in TLS section.
Regards
